### ISSUE TITLE
Some essential files are missing!

### ISSUE THREAD

**Issue by ltp1995** [zychen423/KE-VIST#2] opened 2020-12-02 02:08 UTC
Thanks for your released work! But many important files such as **storyid2concept_tree_noun_and_frame_train.json**, **concept_vocab.pkl** are missing in **/src/stage1/image2term/DataLoader.py** , which are essential to train the model, i am also wondering how to generate these json or pkl files, can you provide more details maybe the preprocessing codes for us?

**Comment by joe32140** [comment] 2020-12-04 05:36
Hi,

We uploaded related files! 
https://github.com/zychen423/KE-VIST/blob/master/src/stage2/data/download_big_data.sh 

Please download them from this script.

**Comment by ltp1995** [comment] 2020-12-07 07:58
> Hi,
> 
> We uploaded related files!
> https://github.com/zychen423/KE-VIST/blob/master/src/stage2/data/download_big_data.sh
> 
> Please download them from this script.

Got it !Thanks again for your shared files.

**Comment by zychen423** [comment] 2020-12-07 12:57
Seems the problem is solved, so I am going to close this issue. 
Thanks @ltp1995 and @joe32140 .

**Closed as completed by zychen423** 2020-12-07 12:57 UTC
